function m31()  {
    var s='';
    s += inicioNivel2('1','INTRODUCCIÓN')+`
<P>Nuestro mundo occidental, tal como lo conocemos hoy, deviene de la matriz cultural de la Antigua Grecia. Desde ella, la racionalidad no sólo se irguió como “la” manera de observar al mundo, sino que fue al tiempo la finalidad de una nueva forma observacional, en que todo se valida y se construye, si es que se quiere participar de la cultura y la civilización, a partir de un nuevo concepto fundacional: la inmutabilidad del ser.</P>
<center><p>“El ser es, el no ser, no es.”</p></center>
<p>No obstante, en el mismo tiempo del advenimiento de la nueva manera de observar y definir el mundo, se produjo una disputa intelectual, que tuvo como adversarios a dos grandes filósofos. Por un lado, estaba Parménides (540-470 a.C.) adalid de la nueva forma de pensar, y por otro, estaba Heráclito de Efeso (546-480 a.C.), a quien no lo convenció esa porfía intelectual por querer descreer de lo que, para él, era tan obvio: que el mundo y la realidad estaban en permanente cambio.</p>
<p>La controversia se fundaba principalmente porque para Parménides, desde su cuna filosófica, lo único apropiado para observar el mundo era el procedimiento lógico y no los sentidos, por ende, el agua del río en que nos bañamos, y que Heráclito decía no sería nunca la misma, para Parménides, sí lo seguía siendo, porque era agua, y nada más. ¿Ahora nos preguntaríamos cómo sabía era la misma agua, y que la persona era la misma?</p>
<p>Para Heráclito, sin embargo, la realidad era dialéctica, porque se construiría a partir del choque de los opuestos: una parte de las cosas siempre cambia, mientras que la otra, no lo hace. En este sentido, Heráclito no abandona por completo aquello que de algún modo estaba inserto en el antiguo régimen anterior al lenguaje escrito: un mundo explicado desde lo auditivo, de lo vivencial y que enmarcaba toda la existencia de las personas en un lenguaje común: la oralidad, porque lo que se decía devenía de las acciones (cuerpo y emociones) y no emergía desde la mente. Un mundo en el que el orador y la acción que realizaba para enunciarla, estaban íntimamente entrelazados.</p>
<p>Aun cuando en el tráfago de la historia, ambas corrientes siguieron palpitando entre los hombres, la de Parménides, se divulgó por el mundo e hizo crecer las ciencias exactas y la filosofía durante los siglos venideros, hasta que su propio germen hizo que ella adquiriera ribetes planetarios.</p>
<p>Durante el siglo XVI, los trabajos de Copérnico, Kepler y Galileo, entre otros, despojaron a nuestro planeta Tierra de su sitial como el centro del Universo, generando en esa época que recién comenzaba a salir de la Edad Media, convulsiones morales, valorativas e ideológicas en una escala propia de una nueva revolución epistemológica.</p>
<p>Un siglo después, en el siglo XVII, Renato Descartes sentenciaría definitivamente que sólo mediante la razón es posible descubrir verdades universales que son innatas, derivándose, a partir de éstas, todas las demás verdades. Así, llegó a establecer una definición sobre el ser humano, en quien lo fundamental, es su ser racional:</p>
<center><p>“Cogito, ergo sum”, “Pienso luego existo”</p></center>
<p>Con ello, Descartes, clausuró inapelablemente, para el mundo científico, cualquier rol de la emocionalidad y la corporalidad en la interpretación del mundo. Se diría así que la visión de Heráclito llegaba a su fin.</p>
<p>Cabe destacar que el filósofo y matemático, contemporáneo y seguidor de Descartes, Blaise Pascal, acotaba, frente al racionalismo cartesiano que “El corazón tiene razones que la razón no entiende”, sugiriendo que ámbitos diferentes a la razón se debaten en el enfrentamiento del ser humano con las “verdades” de la vida.</p>
<p>La culminación del postulado racionalista científico de Descartes se manifestó plenamente en 1687, con la publicación de la obra de Isaac Newton “Philosophiae naturalis principia mathematica”, donde el científico inglés plantea la Ley de la Gravitación Universal, como el gran paradigma científico moderno (cuya gran propuesta implícita es la posibilidad real que afuera e independiente de nuestro plano de observadores existe una realidad “objetivable”), y que no se cuestionaría, sino hasta principios del siglo XX, con la irrupción de la Teoría de la Relatividad de Albert Einstein y la Mecánica Cuántica de Max Planck.</p>
<p>Por otro lado, el fundamental trabajo del naturalista inglés Charles Darwin, “El origen de las especies por medio de la selección natural” publicado en 1859, termina por romper con la tradición que ponía al ser humano, entendido como especie, en el centro de la vida, el conocimiento y la verdad. En él, Darwin establece que la diversidad de especies vivas en la naturaleza, incluida la del ser humano, se explica por modificaciones acumuladas debidas a la evolución a lo largo de la historia de la especie. El ser humano, por tanto, debía tener un ancestro común con otras especies actuales que habían evolucionado de manera diferente.</p>
<p>Estos hitos señalaban a su modo, que aún cuando no seamos el centro del universo, aún cuando provengamos de la evolución de la vida, en su sentido más amplio, aún nos es propia la “razón” y la “objetividad” como criterios de comprensión del mundo y de “lo que nos ocurre”.</p>
<p>Freud, por su parte, en los albores del siglo XX, con su postulado sobre el inconsciente, dirá que nuestro comportamiento no es sólo racional, sino que está impulsado por aspectos no “objetivos” ni racionales, sino provenientes, conforme a las ideas darwinianas de evolución, de determinados instintos o pulsiones instintivas propias de nuestra especie (no individuales puras) no conscientes, aunque sí técnicamente analizables.</p>
<p>Este hecho, el planteamiento de elementos no conscientes que determinarían en gran parte el comportamiento humano, significó entonces, un golpe definitivo a la soberbia occidental que había querido suponer que el ser humano era la piedra de inicio y de tope del universo.</p>
<p>De esta manera, la aceptación de otras maneras posibles de interpretar el comportamiento del ser humano y su relación con el universo quedó abierta desde entonces.</p>
<p>Hoy el nuevo-antiguo paradigma nos conduce ahora a aceptar que la realidad en la que vivimos depende finalmente sólo de nuestro presente como observadores y habitantes de este universo, asumiendo como principal tarea, el reformular nuestra forma de vida, aprendiendo a vivir y a vivenciar, desde ese permanente e inmutable cambio, toda nuestra historia y el devenir de la realidad.</p>
<p>Ahora, parece ser que podemos empezar a entender que “la intuición” u otros estados de conciencia, que el cuestionamiento de la “objetividad” como criterio final del consenso, puede ser también una metodología posible, incorporando tanto el cuerpo como la emocionalidad, abriéndonos a la humildad de “lo que sentimos de verdad”, dejando atrás la arrogancia de la “ciencia racionalista” y de sus paradigmas esclavizantes.</p>
<p>Hoy estamos frente a la posibilidad de una interpretación donde impere más la paz y la armonía en la diversidad legítima, que la guerra de la verdad objetiva.</p>
`+finNivel2()+`
`+inicioNivel2('2','LA RUTA HISTÓRICO-SEMÁNTICA DEL INCONSCIENTE')+`
`+finNivel2();
return s;
}
// INCONSCIENTE NUMINOSO
