function m31()  {
    var s='';
    s += inicioNivel2('1','INTRODUCCIÓN')+`
<P>Nuestro mundo occidental, tal como lo conocemos hoy, deviene de la matriz cultural de la Antigua Grecia. Desde ella, la racionalidad no sólo se irguió como “la” manera de observar al mundo, sino que fue al tiempo la finalidad de una nueva forma observacional, en que todo se valida y se construye, si es que se quiere participar de la cultura y la civilización, a partir de un nuevo concepto fundacional: la inmutabilidad del ser.</P>
<center><p>“El ser es, el no ser, no es.”</p></center>
<p>No obstante, en el mismo tiempo del advenimiento de la nueva manera de observar y definir el mundo, se produjo una disputa intelectual, que tuvo como adversarios a dos grandes filósofos. Por un lado, estaba Parménides (540-470 a.C.) adalid de la nueva forma de pensar, y por otro, estaba Heráclito de Efeso (546-480 a.C.), a quien no lo convenció esa porfía intelectual por querer descreer de lo que, para él, era tan obvio: que el mundo y la realidad estaban en permanente cambio.</p>
<p>La controversia se fundaba principalmente porque para Parménides, desde su cuna filosófica, lo único apropiado para observar el mundo era el procedimiento lógico y no los sentidos, por ende, el agua del río en que nos bañamos, y que Heráclito decía no sería nunca la misma, para Parménides, sí lo seguía siendo, porque era agua, y nada más. ¿Ahora nos preguntaríamos cómo sabía era la misma agua, y que la persona era la misma?</p>
<p>Para Heráclito, sin embargo, la realidad era dialéctica, porque se construiría a partir del choque de los opuestos: una parte de las cosas siempre cambia, mientras que la otra, no lo hace. En este sentido, Heráclito no abandona por completo aquello que de algún modo estaba inserto en el antiguo régimen anterior al lenguaje escrito: un mundo explicado desde lo auditivo, de lo vivencial y que enmarcaba toda la existencia de las personas en un lenguaje común: la oralidad, porque lo que se decía devenía de las acciones (cuerpo y emociones) y no emergía desde la mente. Un mundo en el que el orador y la acción que realizaba para enunciarla, estaban íntimamente entrelazados.</p>
<p>Aun cuando en el tráfago de la historia, ambas corrientes siguieron palpitando entre los hombres, la de Parménides, se divulgó por el mundo e hizo crecer las ciencias exactas y la filosofía durante los siglos venideros, hasta que su propio germen hizo que ella adquiriera ribetes planetarios.</p>
<p>Durante el siglo XVI, los trabajos de Copérnico, Kepler y Galileo, entre otros, despojaron a nuestro planeta Tierra de su sitial como el centro del Universo, generando en esa época que recién comenzaba a salir de la Edad Media, convulsiones morales, valorativas e ideológicas en una escala propia de una nueva revolución epistemológica.</p>
<p>Un siglo después, en el siglo XVII, Renato Descartes sentenciaría definitivamente que sólo mediante la razón es posible descubrir verdades universales que son innatas, derivándose, a partir de éstas, todas las demás verdades. Así, llegó a establecer una definición sobre el ser humano, en quien lo fundamental, es su ser racional:</p>
<center><p>“Cogito, ergo sum”, “Pienso luego existo”</p></center>
<p>Con ello, Descartes, clausuró inapelablemente, para el mundo científico, cualquier rol de la emocionalidad y la corporalidad en la interpretación del mundo. Se diría así que la visión de Heráclito llegaba a su fin.</p>
<p>Cabe destacar que el filósofo y matemático, contemporáneo y seguidor de Descartes, Blaise Pascal, acotaba, frente al racionalismo cartesiano que “El corazón tiene razones que la razón no entiende”, sugiriendo que ámbitos diferentes a la razón se debaten en el enfrentamiento del ser humano con las “verdades” de la vida.</p>
<p>La culminación del postulado racionalista científico de Descartes se manifestó plenamente en 1687, con la publicación de la obra de Isaac Newton “Philosophiae naturalis principia mathematica”, donde el científico inglés plantea la Ley de la Gravitación Universal, como el gran paradigma científico moderno (cuya gran propuesta implícita es la posibilidad real que afuera e independiente de nuestro plano de observadores existe una realidad “objetivable”), y que no se cuestionaría, sino hasta principios del siglo XX, con la irrupción de la Teoría de la Relatividad de Albert Einstein y la Mecánica Cuántica de Max Planck.</p>
<p>Por otro lado, el fundamental trabajo del naturalista inglés Charles Darwin, “El origen de las especies por medio de la selección natural” publicado en 1859, termina por romper con la tradición que ponía al ser humano, entendido como especie, en el centro de la vida, el conocimiento y la verdad. En él, Darwin establece que la diversidad de especies vivas en la naturaleza, incluida la del ser humano, se explica por modificaciones acumuladas debidas a la evolución a lo largo de la historia de la especie. El ser humano, por tanto, debía tener un ancestro común con otras especies actuales que habían evolucionado de manera diferente.</p>
<p>Estos hitos señalaban a su modo, que aún cuando no seamos el centro del universo, aún cuando provengamos de la evolución de la vida, en su sentido más amplio, aún nos es propia la “razón” y la “objetividad” como criterios de comprensión del mundo y de “lo que nos ocurre”.</p>
<p>Freud, por su parte, en los albores del siglo XX, con su postulado sobre el inconsciente, dirá que nuestro comportamiento no es sólo racional, sino que está impulsado por aspectos no “objetivos” ni racionales, sino provenientes, conforme a las ideas darwinianas de evolución, de determinados instintos o pulsiones instintivas propias de nuestra especie (no individuales puras) no conscientes, aunque sí técnicamente analizables.</p>
<p>Este hecho, el planteamiento de elementos no conscientes que determinarían en gran parte el comportamiento humano, significó entonces, un golpe definitivo a la soberbia occidental que había querido suponer que el ser humano era la piedra de inicio y de tope del universo.</p>
<p>De esta manera, la aceptación de otras maneras posibles de interpretar el comportamiento del ser humano y su relación con el universo quedó abierta desde entonces.</p>
<p>Hoy el nuevo-antiguo paradigma nos conduce ahora a aceptar que la realidad en la que vivimos depende finalmente sólo de nuestro presente como observadores y habitantes de este universo, asumiendo como principal tarea, el reformular nuestra forma de vida, aprendiendo a vivir y a vivenciar, desde ese permanente e inmutable cambio, toda nuestra historia y el devenir de la realidad.</p>
<p>Ahora, parece ser que podemos empezar a entender que “la intuición” u otros estados de conciencia, que el cuestionamiento de la “objetividad” como criterio final del consenso, puede ser también una metodología posible, incorporando tanto el cuerpo como la emocionalidad, abriéndonos a la humildad de “lo que sentimos de verdad”, dejando atrás la arrogancia de la “ciencia racionalista” y de sus paradigmas esclavizantes.</p>
<p>Hoy estamos frente a la posibilidad de una interpretación donde impere más la paz y la armonía en la diversidad legítima, que la guerra de la verdad objetiva.</p>
`+finNivel2()+`
`+inicioNivel2('2','LA RUTA HISTÓRICO-SEMÁNTICA DEL INCONSCIENTE')+`
<p>El término “inconsciente” fue empleado por primera vez como término técnico en lengua inglesa en 1751, -con la significación de no consciente-, por el jurista escocés Henry Lord Kames (1696-1782). En el siglo XVII Leibniz habla de “pequeñas percepciones de las que no tenemos ninguna conciencia”.</p>
<p>Mientras en el mundo James Watt inventaba la máquina de vapor, en 1775 se inicia una de las transformaciones más profundas en los sistemas de trabajo y de la estructura de la sociedad. A partir de entonces, se comienza un tránsito socioeconómico y cultural, que daría paso del viejo mundo rural al de las ciudades, del trabajo manual al de la máquina y al estudio del conocimiento.</p>
<p>El concepto ‘inconsciente’ se popularizó más tarde en Alemania, en la época romántica (mediados del siglo XIX), designándolo como un depósito de imágenes mentales, una suerte de fuente de pasiones, cuyo contenido escapaba a la conciencia. Textos tales como: “Reino crepuscular de la conciencia” (Coleridge), en el “Más allá del psiquismo” (Goethe), en “Los secretos rincones del corazón y de las sombras espirituales donde el sol nunca penetra” (Woodworth).</p>
<p>Introducido en la lengua francesa hacia 1860 por el escritor suizo Henri Amiel (1821-1881), bajo el significado de “vida inconsciente”, o depósito donde se encuentran escondidos los secretos del ser humano. El término “inconsciente” fue admitido así en el Dictionnaire de l'Académie française en 1878. Acaso como parte de las consecuencias de la Primera Guerra Mundial (1914-1918), conflicto armado que produjo más de 10 millones de muertos, instalándose como el conflicto más sangriento de la historia hasta entonces, y que el mundo fue conociendo aterrorizado, es que en 1915, el doctor austro-húngaro Sigmund Freud (1856-1939), propone una teoría que descolocaría el “ego” de la humanidad.</p>
<p>En su publicación “Lo inconsciente”, Freud propone que el ser humano no actúa sólo de manera racional como asumió Descartes, sino en gran medida lo haría de manera inconsciente. Según Freud, el inconsciente se hace presente como un elemento que actúa “por debajo” de la conciencia y que es capaz de movilizar al sujeto sin que éste advierta el origen de su decisión/acción. (Del Volumen XIV - Trabajos sobre metapsicología, y otras obras (1914-1916), «Contribución a la historia del movimiento psicoanalítico»)</p>
<p>Desde su óptica médica, -como investigador, se centró en el campo de la neurología, derivando progresivamente sus investigaciones hacia la vertiente psicológica de las afecciones mentales-, Freud quiso designar bajo el término Inconsciente, en primer lugar, todo contenido mental que no se encuentra en la conciencia. Pero, en segundo lugar, lo utilizó para designar uno de los sistemas del aparato psíquico, como la parte no-consciente que sólo puede aflorar a la consciencia, con grandes esfuerzos por parte del sujeto. Tras sus estudios, Freud llegó a sostener que en el Inconsciente se encuentran entonces los deseos, instintos y recuerdos que el sujeto reprime por resultarle inaceptables, fundamentalmente a causa de sus propias valoraciones morales.</p>
<p>“La represión, por su parte, tiene gran importancia en el conocimiento de lo inconsciente. De acuerdo con Freud, las personas experimentan a menudo pensamientos y sentimientos que son tan dolorosos que no pueden soportarlos. Estos pensamientos y sentimientos (al igual que los recuerdos asociados a ellos) no pueden, según sostuvo, ser expulsados de la mente, pero sí pueden ser expulsados del consciente para formar parte del inconsciente, manteniendo lo reprimido su efectividad psíquica y retornando en forma de alguna de sus producciones.” (Biografía S. Freud, Wikipedia).</p>
<p>De ahí que el Inconsciente posea una dimensión biográfica, y se nutra de la memoria, especialmente de los hechos vividos durante la infancia y se genera, en el encuentro de las tendencias instintivas (pulsiones diría Freud) con los ecofactores que estimulan o inhiben los potenciales personales. Así para Freud, el Inconsciente es la capa más profunda de la mente y se identifica en gran medida con aquel elemento de la psiquis de cada persona: el ego.</p>
<p>Freud imaginó y definió así el Inconsciente como una estructura que se mide entonces por sus efectos, y se deduce por las observaciones que se puede hacer de él: actos fallidos, tropiezos, datos que proporcionan los sueños, etc.</p>
<p>En medio de la postcrisis de la Primera Guerra, Carl Gustav Jung (1875-1961), ya alejado definitivamente de su maestro Freud, de quien muchos años atrás se creía iba a ser el “heredero lógico”, publica uno de sus textos más característicos, “Los arquetipos y el inconsciente colectivo” (1934).</p>
<p>Para llegar a esta publicación, Jung se dio primero a la titánica tarea de desentrañar “los personajes” que, según sus análisis daban cuerpo a las acciones que afloraban desde el Inconsciente. A fin de agilizar su experimento con el inconsciente recurrirá a representarse mentalmente una pendiente con la finalidad de captar mejor sus fantasías y descender a los estratos más profundos de la psique. De ahí surgirá el episodio en donde llega a vislumbrar tres nuevas figuras. Elías, arquetipo del Viejo Sabio, encarnación del Logos, el elemento racional; Salomé, arquetipo del Ánima, o arquetipo de lo femenino, representada ciega, encarnación de Eros, el elemento erótico; y una serpiente negra, que anunciaba de nuevo el mito del Héroe.</p>
<p>Finalmente, y desde esta misma triada emergerá una nueva figura derivada del arquetipo del Viejo Sabio a la que llamará Filemón, describiéndola como «un pagano que aportaba una influencia egipcio-helenística con matiz gnóstico», «un gurú», «un espíritu», «un maestro del alma».” (Biografía, C. G. Jung, Wikipedia).</p>
<p>“Filemón y otras figuras de la fantasía me llevaron al convencimiento de que existen otras cosas en el alma que no hago yo, sino que ocurren por sí mismas y tienen su propia vida.” (Carl Gustav Jung, “Recuerdos, sueños, pensamientos).</p>
<p>Será entonces Filemón, quien diera lugar a su recapitulación teórica y a la validación de la existencia autónoma de los arquetipos, más allá de los complejos, extendiendo a lo colectivo la adjetivación personal de lo inconsciente freudiano.</p>
<p>La psicología analítica creada por Jung parte de una estructuración psíquica constituida por un inconsciente colectivo en la psique de cada individuo, de tal modo que “la consciencia centralizada en el Yo ya no establecerá relaciones exclusivas de reciprocidad a nivel de los complejos de lo inconsciente personal, sino que habrá de vérselas a su vez con los constituyentes transpersonales de lo inconsciente colectivo: los arquetipos.” (C. G. Jung, Obra Completa volumen 9/1: Los arquetipos y lo inconsciente colectivo, Sobre los arquetipos de lo inconsciente colectivo).</p>
<p>Desde estos pensamientos, Jung se dedica a estudiar los arquetipos cuya aparición onírica es común a toda la humanidad. Su objetivo es la revelación del self (el sí mismo) a través de lo que él llamó el Proceso de Individuación. Su teoría llegará a establecer que existe un lenguaje común a los seres humanos de todos los tiempos y lugares del mundo, constituido por símbolos primitivos con los que se expresa un contenido de la psiquis que está más allá de la razón, “el lenguaje simbólico”, nutriente de las narrativas mitológicas y teológicas de todos los pueblos a través de la historia de la humanidad.</p>
<p>El concepto de arquetipo, introducido por C. G. Jung como término dentro del campo de lo psíquico, alude al hecho de que los seres humanos compartimos una serie de experiencias, en el curso de nuestra evolución, que han quedado, por su naturaleza colectiva, incorporadas en la memoria de la humanidad como patrones de comprensión de la realidad.</p>
<p>Estos esquemas son pura energía inconsciente que busca realizarse y lo hace, por ejemplo, por medio de los símbolos. Expresan un orden de saber que la conciencia del hombre desconoce, pero que existe como verdad en las profundidades de su alma. (Eduardo H. Grecco, Interpretación iniciática de la décima revelación, Ediciones Continente, Buenos Aires, 1996).</p>
<p>De estas propuestas, se desprende que finalmente Jung sostuviera que los modos de acceso al Inconsciente Colectivo debían ser:
<ul>
<li>Un acabado estudio sobre los símbolos de transformación.</li>
<li>Los Arquetipos que conducen y están relacionados al proceso de individuación (self).</li>
<li>Las Expresiones del Inconsciente a través del Arte: la pintura, poesía o velatorios tribales.</li>
<li>El análisis de los sueños orientados (sin interpretación).</li>
<li>Ceremonias y trabajos con los mitos.</li>
</ul></p>
`+finNivel2()+`
`+inicioNivel2('3','ANTECEDENTES DEL CONCEPTO “NUMINOSO”')+`
<p>El antropólogo y estudioso de las teologías comparadas, el alemán Rudolf Otto (1869-1937), en su libro “Lo sagrado”, publicado inicialmente en 1917 como Das Heilige (Lo Sagrado), define el concepto de lo sagrado como aquello que es numinoso, misterioso. Explicó el concepto de lo misterioso como una «experiencia no-racional y no-sensorial o el presentimiento cuyo centro principal e inmediato está fuera de la identidad». (A diferencia de Biodanza).</p>
<p>Otto utilizó la palabra "numen" para describir al ser sagrado supremo a quien todas las religiones tienden a intentar conocer y el que generó el primer sentimiento religioso por medio de experiencias religiosas o hierofanías.</p>
<p>El término hierofanías fue utilizado por Mircea Eliade en su obra “Tratado de Historia de las Religiones” para referirse a una toma de consciencia de la existencia de lo sagrado cuando éste se manifiesta a través de los objetos de nuestro cosmos habitual como algo completamente opuesto al mundo profano.</p>
<p>Para traducir el acto de manifestación de lo sagrado, Eliade propone el término Hierofanía, ya que se refiere únicamente a aquello que corresponde a lo sagrado de lo que se nos muestra.</p>
<p>Según explica Eliade, "para aquellos que tienen una experiencia religiosa, la Naturaleza en su totalidad es susceptible de revelarse como sacralidad cósmica. El Cosmos en su totalidad puede convertirse en una hierofanía. El hombre de las sociedades arcaicas tiene tendencia a vivir lo más posible en lo sagrado o en la intimidad de los objetos consagrados. En contraste, la sociedad moderna habita un mundo desacralizado”.</p>
<p>Lo numinoso lleva adherido entonces una percepción de ‘majestad’ que provoca en el alma la sensación enriquecedora de una energía trascendente, que excluye toda interpretación racional.</p>
<p>"La nostalgia por el paraíso" es un término también utilizado por Mircea Eliade para ayudar a la comprensión de lo numinoso. Esta idea se basaba en la teoría de que una persona tiene una especie de ansia de perfección o “de paraíso”, lo que crea una plataforma para la experiencia de lo numinoso.</p>
<p>Rudolf Otto nos llama la atención de cómo un concepto inefable como lo numinoso (Sujeto), es captado y designado con clara precisión a través de predicados como: espíritu, unidad esencial, voluntad, etc., de modo que son pensados al mismo tiempo en correspondencia con predicados racionales que el ser humano ha descubierto en sí mismo. Todos estos predicados son conceptos claros y distintos, son accesibles al pensamiento, al análisis intelectual y aún a la definición. No por esto agotan la esencia de lo numinoso, no agotan tampoco la idea de lo numinoso, ya que ellos justamente valen y son solo por algo irracional y en algo irracional (inefable).</p>
<p>Momentos de “Lo Numininoso”: Misterium-Tremendum-Majestas-BeatificanteEnergicum.</p>
<p>Rudolf Otto sugiere que lo numinoso tiene la categoría de Misterioso, Tremendo, Majestuoso, Sagrado, Beatificante, Enorme, Enérgico (entre otras, ya que es inefable). En el encuentro con lo numinoso y su grandeza, surge el sentimiento de criatura, que se hunde y desaparece en su propia nada frente aquello que está por encima de toda criatura (el tremendo misterio), un sentimiento de sí mismo, es decir, el sentimiento de una determinada determinación de “mi mismo”, de mi dependencia del misterio, cuando se siente algo de carácter numinoso puede surgir en el ánimo de “sentimiento de criatura” un “temeroso respeto” (frente a lo misterioso y tremendo).</p>
<p>De acuerdo con Rudolf Otto, lo numinoso se caracterizaría por distintos elementos que él designa en latín. Algunos de estos son:</p>
<h4>Mysterium Tremendum</h4>
<ul>
<li>En tanto <i>Mysterium</i>, se refiere a que es imposible de explicar con palabras, es decir, inexpresable y enteramente diferente a cualquier otra experiencia de vida, porque su sentido supera los límites impuestos por el ordenamiento racional del lenguaje, puede por momentos excitar y llenar el ánimo de manera que casi trastorna los sentidos, este sentimiento puede penetrar el ánimo con dulce flujo en forma de devoción absorta del temple del ánimo sereno y en suspenso, puede llevar a la embriaguez, al éxtasis, tiene formas salvajes y demoniacas (luz y sombra), y tiene su desarrollo en formas finas purificadas, puede convertirse en el temblor humilde y silencioso de “la criatura”.
<br><i>“Yo que he comenzado a hablar, yo, que soy polvo y ceniza”</i>. (Génesis 18, 27)</li>
<li><i>Tremendum:</i> Como caracterización próxima a Tremendum puede adjetivarse tremor, que en sí es solo temor, sin embargo solo analógica para un sentimiento reactivo específico que tiene por cierto semejanza con el temor, pero que en sí mismo es algo completamente distinto a atemorizarse, es un terror lleno de íntimo espanto, tal como no puede producir nada creado, ni aún lo más amenazador ni peligroso, algo “Tremendo”, produce un temeroso respeto, no es un miedo natural habitual sino ya una primera palpitación y sospecha de lo misterioso. Lo Tremendum, denota el temor humano ante la presencia de una fuerza poderosa, tremenda, terrible, formidable, digna de respeto. El temor como una reacción ante una realidad completamente diferente. Lo “Enorme” para Rudolf Otto es simplemente aquello que es muy grande por su medida o cualidad, para nosotros, es en primer término “lo no seguro”, lo desasogante.</li>
<li><i>Majestas</i> (El momento de lo dominante): El momento de lo tremendo es descrito plenamente como “Tremenda Majestas”, el sentimiento de criatura se relaciona con un sentimiento de pertenencia y dominación absoluta de lo numinoso, como contraste a la dominación sentida se exterioriza con el sentimiento del propio hundirse, ser tierra y ceniza, lleva por una parte aniquilación del Yo y por otra a la realidad única y total de lo trascendente. Majestas, se refiere a que provoca o induce una actitud reverencial.</li>
<li>Los últimos momentos de lo Tremendum y de las Majestas se topan con un tercer momento. “Lo enérgico” es aquel momento del numen, que cuando es experimentado, activa el espíritu del ser humano, lo llena de una enorme tensión y dinamismo. Sea en celo contra el mundo y la carne sea en el hacer y obrar heroicos en que la agitación palpita hacia afuera. Lo enérgico está vigorosamente vivo, sin descanso o retroceso.</li>
</ul>
<p>El momento de lo Misterioso en lo numinoso puede sobrepasar al de lo Tremendum en las vivencias afectivas y ocupar el primer plano con tanto vigor que el sentimiento de lo Tremendum casi desaparece. Al misterio restado del momento de lo Tremendum, Rudolf Otto lo llama lo admirable.</p>
<p>Ya hemos visto la distancia que impone lo Tremendum, pero por otra parte es evidentemente algo peculiar, atrayente, cautivante, fascinante, que aparece en una extraña mezcla de contraste y armonía con el momento distanciador de lo Tremendum, la criatura que se estremece ante lo numinoso con humilde timidez, tiene siempre al mismo tiempo un impulso de volverse hacia el, no es solo admirable es también fascinante, las representaciones racionales que van paralelas a estos momentos irracionales de lo fascinante y lo esquematizan son: el amor, la misericordia, la compasión, la caridad, todos momentos naturales de la expresión anímica común, solo que pensados en su perfección.</p>
<ul>
<li>En tanto <i>Fascinans</i> (lo fascinante tiene un valor beatificante), entendido como gracia y misericordia deslumbrante y abarcadora.</li>
<li><i>La Gracia</i> (Beatificante). Lo profundamente maravilloso que yace en el misterio beatífico de la experiencia del numen, al identificarse con el numen, “permanecer en posesión numinosa, el misterio es vivido en su cualidad íntima y en verdad como algo que da una dicha inaudita”. El temor se traduciría en veneración o respeto reverencial ante lo inefable que se manifiesta como un "estremecimiento" que supera todo miedo o temor paralizante.<br>
<center>“Ser bienaventurado, delicia infinita,<br>
Abismo de la dicha más perfecta<br>
Majestad Eterna, espléndido sol,<br>
Que no conoce cambio, ni alteración”</center><br>
<span style="text-align:right">Bernard de Cluny</span></li>
<ul>
<p>Rudolf Otto describe lo numinoso como un encuentro impresionante lleno de la realidad última, un misterio que es a la vez terrorífico y fascinante, y lo coloca como el atributo mayor de la experiencia religiosa, desde donde lo numinoso se nos ofrece como una experiencia inefable.</p>
<p>Carl Jung tomaría desde Otto también el concepto numinoso con relación al carácter de los Arquetipos, agregando que “inmediatamente, el temor es superado de forma chocante, sorprendente” por medio de la misericordia (sentir o irradiar afecto entrañable) y la gracia. Jung adhiere a la definición de Otto sobre el carácter numinoso en tanto comparte que es un ámbito de “lo fuera de lo común”, un modo no ordinario o elevado de conciencia.</p>
<p>Jung hace referencia además a la importancia de la presencia de la sombra en lo numinoso, y que en ella misma estaría la sanación, donde tanto los aspectos positivos y negativos de la numinosidad pueden ser potencialmente útiles para el desarrollo humano psicológico y espiritual.</p>
<p>De acuerdo con Jung también, a través de lo que él describe metafóricamente como el proceso "alquímico" del desarrollo humano, el Ser (Self) experimenta algo parecido al desmembramiento de Osiris (Mito de Isis & Osiris), se "muere" y se desgarra, pero a través de una experiencia numinosa puede ser también reconfigurado, reconstituido, en sus palabras, puede ser “redimido”. En lenguaje psicológico, se restaura con un nuevo y equilibrado sentido de la vida.</p>
<p>“La necesaria y requerida reacción de lo inconsciente colectivo se expresa, en representaciones formadas arquetípicamente. El encuentro con uno mismo significa en un principio el encontrarse con la propia sombra. Por otra parte, esa sombra es un paso angosto, una puerta estrecha cuya precaria angostura no puede eludir nadie que descienda a lo hondo del pozo. Pero hay que conocerse a sí mismo para saber quién se es, puesto que lo que viene después de la muerte es, inesperadamente, una ilimitada extensión llena de inconcebible imprecisión, en la que al parecer no hay ni fuera ni dentro, ni arriba ni abajo, ni aquí ni allá, ni mío ni tuyo, ni bueno ni malo. Es el mundo del agua, en el que flota, en suspenso, todo lo vivo, donde comienza el reino del «simpático», del alma de todo lo vivo, donde yo soy inseparable y soy éste y aquél, donde experimento en mí al otro y el otro me experimenta a mí como al yo.” (C. G. Jung, Obra Completa volumen 9/1: Los arquetipos y lo inconsciente colectivo, Sobre los arquetipos de lo inconsciente colectivo).</p>
<p>Este último aserto respecto de la vivencia del sí mismo desde el encuentro con otro, llevaría a otro filosofo contemporáneo, Emmanuel Levinas (1906-1995), desde su propia experiencia (campo de concentración nazi en Hannover) a sostener que, en base a la sacralidad de la experiencia de vida, era una aspiración equívoca e inconducente la premisa ontológica de “conocerse a sí mismo, sin transitar ineluctablemente por el encuentro con otro semejante”, donde según él, “afloran las verdaderas noticias del sí mismo”.</p>
<p>“Levinas propuso un humanismo del otro hombre, del hombre que se responsabiliza y responde totalmente por el otro: desde el momento en que el otro me mira, yo soy responsable de él sin ni siquiera tener que tomar responsabilidades en relación con él; su responsabilidad me incumbe. Es una responsabilidad que va más allá de lo que yo hago”.</p>
<p>Así pasamos, con Levinas, de un yo cerrado (ego cartesiano) a un yo abierto, ya que la filosofía a partir de ahora no empezará en el Yo, sino en el Otro. Pues, ¿cuándo soy yo? Cuando otro me nombra. Si nadie nos nombra, no somos nada.</p>
<p>Podemos sustituir, de esta manera el "pienso, luego soy/existo", que enunciaba Descartes, por "soy amado, soy nombrado, luego soy".</p>
<p><sub>Artículo de Paula Gil Jiménez, estudiante de cuarto de Filosofía en la Universidad de Valencia, España, sobre</sub> <a target="_blank" href="http://deautores.blogspot.com/2006/08/teora-tica-de-lvinas.html">“LA TEORÍA ÉTICA DE LÉVINAS”</a>.</p>
<p>“El primer fundamento de la filosofía de Levinas nace de una constatación sagrada, el principio no es como en la filosofía cartesiana se empeñó en mostrar, el pensamiento, sino la relación. Poner al inicio de toda experiencia la relación, el pensamiento implica un aprehender, que se adueña de lo aprendido. Si comenzamos en cambio por la relación, las cosas cambian, encontrarnos con el otro es nombrarlo en una relación que rompe la posesividad y al romperla, trasciende la distancia entre el tú y el yo.</p>
<p>Lo segundo que sugiere Levinas es: la desnudez del rostro del otro me manifiesta su vulnerabilidad, su indefensión, su impotencia y el miedo, me prohíbe humillarlo o matarlo; me pide que lo tome a su cuidado.</p>
<p>Lo tercero que nos muestra que es la relación auténtica, la experiencia irreductible que se da en el enfrentamiento cara a cara, es en ese encuentro donde me pide que me haga responsable de él hasta la redención. Lo humano realmente comienza cuando soy capaz de cargar con esta responsabilidad del otro, cuando sus desgracias y miserias me persiguen y me siento interpelado, emplazado a responder a sus miserias y a las miserias de los otros.</p>
<p>La libertad para Levinas se encuentra en la capacidad de posponer la traición. La capacidad de posponer la traición solo puede explicarse por algo que trasciende al mismo Yo, y que se manifiesta en primer lugar en los otros.</p>
<p>No hay nada en este mundo capaz de hacernos renunciar al yo, excepto el rostro de los otros.</p>
<p>Aunque toda la creación proclama la grandeza del misterio, nadie la proclama mejor que el prójimo.</p>
<p>El carácter del encuentro para Levinas: la relación con el otro puede alcanzar estado de epifanía en el encuentro con la mirada y al entrar en comunión, la manifestación de lo sagrado del otro. El vínculo con el otro tiene la cualidad de lo infinito, es inabarcable, el encuentro es la posibilidad de rescatar lo divino del otro”. (Extractos de la tesis para obtención del título de “Facilitador de Biodanza” Escuela Cordillera de los Andes, nombre de la tesis “La ética de Levinas, una ética para Biodanza” Autor: Rodolfo Cesar Carter Canales, Año 2009).</p>
`+finNivel2()+`
`+inicioNivel2('4','')+`
`+finNivel2()+`
`+inicioNivel2('5','')+`
`+finNivel2()+`
`+inicioNivel2('VIDEOS','MARATONA PEDRO LABBE SEP-2020')+`
<embed type="video/webm" src="INuminoso01.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 1/8<br><br>
<embed type="video/webm" src="INuminoso02.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 2/8<br><br>
<embed type="video/webm" src="INuminoso03.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 3/8<br><br>
<embed type="video/webm" src="INuminoso04.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 4/8<br><br>
<embed type="video/webm" src="INuminoso05.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 5/8<br><br>
<embed type="video/webm" src="INuminoso06.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 6/8<br><br>
<embed type="video/webm" src="INuminoso07.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 7/8<br><br>
<embed type="video/webm" src="INuminoso08.mp4" width="400" height="300" autostart="false"><br>
Maratona Inconsciente Numinoso - Pedro Labbe - Parte 8/8<br><br> 
`+finNivel2();
return s;
}
// INCONSCIENTE NUMINOSO
